version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependancies
          command: npm install
      - run:
          name: Build
          command: npm run build

workflows:
  heroku_deploy:
    jobs:
    - build
    - heroku/deploy-via-git:
        app-name: $HEROKU_APP_NAME
        requires: 
            - build
        filters: 
            branches: 
                only: develop
