version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependancies
          command: npm install
      - run:
          name: Build
          command: npm run build


  deploy:
    machine: 
      enabled: true
    working_directory: ~/rep
    steps:
      - checkout
      - run:
          name: Setup heroku 
          command: heroku git:remote -a kavi-reactjs
      - run:
          name: Deploy the app
          command: git push heroku main

workflows:
  heroku_deploy:
    jobs:
    - build
    - deploy:
        requires:
          - build
        filters:
          branches:
            only: main

